# Generated by Django 5.2.7 on 2025-12-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='number_of_openings',
            field=models.IntegerField(blank=True, help_text='Number of positions available', null=True),
        ),
    ]
