# Generated by Django 5.2.7 on 2025-12-18 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='users_job_status_7da34d_idx',
            old_name='users_job_status_7e99c1_idx',
        ),
        migrations.RenameIndex(
            model_name='trainingprogram',
            new_name='users_train_categor_7585bb_idx',
            old_name='users_train_categor_276429_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(help_text='Job category - will be set to null if category is deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='users.category'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='category',
            field=models.ForeignKey(help_text='Training category - will be set to null if category is deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_programs', to='users.category'),
        ),
    ]
