# Generated by manually for default categories

from django.db import migrations


def create_default_categories(apps, schema_editor):
    """Create default categories from hardcoded choices"""
    Category = apps.get_model('users', 'Category')
    
    default_categories = [
        {'name': 'Healthcare', 'slug': 'healthcare', 'description': 'Healthcare and medical services'},
        {'name': 'Technology', 'slug': 'technology', 'description': 'IT, software, and technology services'},
        {'name': 'Construction', 'slug': 'construction', 'description': 'Construction and building trades'},
        {'name': 'Retail', 'slug': 'retail', 'description': 'Retail sales and customer service'},
        {'name': 'Hospitality', 'slug': 'hospitality', 'description': 'Hotels, restaurants, and tourism'}, 
        {'name': 'Manufacturing', 'slug': 'manufacturing', 'description': 'Manufacturing and production'},
        {'name': 'Education', 'slug': 'education', 'description': 'Education and training'},
        {'name': 'Finance', 'slug': 'finance', 'description': 'Finance, banking, and accounting'},
        {'name': 'Soft Skills', 'slug': 'soft-skills', 'description': 'Communication, leadership, and interpersonal skills'},
        {'name': 'Other', 'slug': 'other', 'description': 'Other categories'},
    ]
    
    for cat_data in default_categories:
        Category.objects.create(**cat_data)


def reverse_default_categories(apps, schema_editor):
    """Remove default categories"""
    Category = apps.get_model('users', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_category_model'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_default_categories),
    ]
