# Generated by Django 5.2.7 on 2025-12-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_populate_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_pdf_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL of resume PDF'),
        ),
    ]
