# Generated by Django 5.2.7 on 2025-12-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_resume_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_suggestions',
            field=models.JSONField(blank=True, default=list, help_text="AI's suggestions"),
        ),
        migrations.AddField(
            model_name='resume',
            name='section_status_data',
            field=models.JSONField(blank=True, default=dict, help_text="AI's section completeness assessment"),
        ),
    ]
