# Generated by Django 5.2.7 on 2025-12-21 00:51

from django.db import migrations, models


def migrate_is_verified_to_status(apps, schema_editor):
    """Migrate existing is_verified boolean to status field"""
    Employer = apps.get_model('users', 'Employer')
    
    # Update all employers based on their is_verified value
    for employer in Employer.objects.all():
        if employer.is_verified:
            employer.status = 'approved'
        else:
            employer.status = 'pending'
        employer.save()


def reverse_migration(apps, schema_editor):
    """Reverse migration - convert status back to is_verified"""
    Employer = apps.get_model('users', 'Employer')
    
    for employer in Employer.objects.all():
        employer.is_verified = (employer.status == 'approved')
        employer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_revert_employer_auto_verification'),
    ]

    operations = [
        # Step 1: Add the new status field (nullable initially to allow for data migration)
        migrations.AddField(
            model_name='employer',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended')], 
                default='pending', 
                max_length=20,
                null=True  # Temporarily allow null
            ),
        ),
        
        # Step 2: Migrate existing data from is_verified to status
        migrations.RunPython(migrate_is_verified_to_status, reverse_migration),
        
        # Step 3: Make status non-nullable now that data is migrated
        migrations.AlterField(
            model_name='employer',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended')], 
                default='pending', 
                max_length=20
            ),
        ),
        
        # Step 4: Remove old fields
        migrations.RemoveField(
            model_name='employer',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='verification_date',
        ),
    ]
