# Generated by Django 5.2.7 on 2025-12-21 00:57

from django.db import migrations, models


def update_status_terminology(apps, schema_editor):
    """Update existing status values to new terminology"""
    Employer = apps.get_model('users', 'Employer')
    
    # Update all employers with old terminology
    Employer.objects.filter(status='approved').update(status='verified')
    Employer.objects.filter(status='suspended').update(status='banned')


def reverse_status_terminology(apps, schema_editor):
    """Reverse terminology update"""
    Employer = apps.get_model('users', 'Employer')
    
    # Revert to old terminology
    Employer.objects.filter(status='verified').update(status='approved')
    Employer.objects.filter(status='banned').update(status='suspended')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_employer_status_field'),
    ]

    operations = [
        # First update the data
        migrations.RunPython(update_status_terminology, reverse_status_terminology),
        
        # Then update the field definition
        migrations.AlterField(
            model_name='employer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('banned', 'Banned')], default='pending', max_length=20),
        ),
    ]
