# Generated by Django 5.2.7 on 2025-12-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_update_employer_status_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprovider',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='trainingprovider',
            name='verification_date',
        ),
        migrations.AddField(
            model_name='trainingprovider',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('banned', 'Banned')], default='pending', max_length=20),
        ),
    ]
