# Generated by Django 5.2.7 on 2025-12-22 19:08

from django.db import migrations, models


def migrate_to_status(apps, schema_editor):
    """Migrate existing approval_status and is_verified to status field"""
    Agency = apps.get_model('users', 'Agency')
    
    for agency in Agency.objects.all():
        # Priority: if is_verified = True, set to 'verified'
        # Otherwise use approval_status mapping
        if agency.is_verified:
            agency.status = 'verified'
        elif agency.approval_status == 'approved':
            agency.status = 'verified'
        elif agency.approval_status == 'rejected':
            agency.status = 'banned'
        else:  # pending or any other value
            agency.status = 'pending'
        agency.save()


def reverse_migration(apps, schema_editor):
    """Reverse migration - convert status back"""
    Agency = apps.get_model('users', 'Agency')
    
    for agency in Agency.objects.all():
        if agency.status == 'verified':
            agency.is_verified = True
            agency.approval_status = 'approved'
        elif agency.status == 'banned':
            agency.is_verified = False
            agency.approval_status = 'rejected'
        else:  # pending
            agency.is_verified = False
            agency.approval_status = 'pending'
        agency.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_trainingprovider_status_field'),
    ]

    operations = [
        # Step 1: Add the new status field (nullable initially)
        migrations.AddField(
            model_name='agency',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('verified', 'Verified'), ('banned', 'Banned')], 
                default='pending', 
                max_length=20,
                null=True
            ),
        ),
        
        # Step 2: Migrate existing data
        migrations.RunPython(migrate_to_status, reverse_migration),
        
        # Step 3: Make status non-nullable
        migrations.AlterField(
            model_name='agency',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('verified', 'Verified'), ('banned', 'Banned')], 
                default='pending', 
                max_length=20
            ),
        ),
        
        # Step 4: Remove old fields
        migrations.RemoveField(
            model_name='agency',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='verification_date',
        ),
    ]
