# Generated by Django 5.2.7 on 2026-01-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_phone_to_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaluser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referreduser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
