# Generated by Django 5.2.7 on 2026-01-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_generaluser_date_of_birth_referreduser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='hired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='hired_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='hired_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
