# Generated by Django 5.2.7 on 2026-01-20 02:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_jobapplication_hired_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('training_enrolled', 'Training Enrollment'), ('certificate_uploaded', 'Certificate Uploaded'), ('certificate_verified', 'Certificate Verified'), ('certificate_rejected', 'Certificate Rejected'), ('job_applied', 'Job Application Submitted'), ('application_interview', 'Interview Scheduled'), ('application_hired', 'Application Hired'), ('application_rejected', 'Application Rejected'), ('welcome', 'Welcome Notification'), ('new_enrollment', 'New Training Enrollment'), ('certificate_pending', 'Certificate Pending Verification'), ('new_application', 'New Job Application'), ('new_trainer_pending', 'New Trainer Pending Approval'), ('new_employer_pending', 'New Employer Pending Approval'), ('new_agency_pending', 'New Agency Pending Approval'), ('referred_user_paid', 'Referred User Completed Payment'), ('general_user_paid', 'General User Completed Payment'), ('new_job_posted', 'New Job Posted'), ('new_training_created', 'New Training Created')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='users_notif_recipie_2469dd_idx'), models.Index(fields=['recipient', '-created_at'], name='users_notif_recipie_458498_idx')],
            },
        ),
    ]
