# Generated by Django 5.2.7 on 2026-02-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_manualcertificate_manualinterview_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualinterview',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='manualcertificate',
            name='certificate_file',
        ),
        migrations.AddField(
            model_name='manualcertificate',
            name='certificate_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='manualinterview',
            name='interview_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='manualinterview',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='manualinterview',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualinterview',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
