# Generated by Django 5.2.7 on 2026-02-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_manualinterview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtraining',
            name='certificate_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='manualtraining',
            name='certificate_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
