# Generated by Django 5.2.7 on 2026-03-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_manualtraining_certificate_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualjobapplication',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualjobapplication',
            name='interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
