# Generated by Django 5.2.7 on 2026-03-01 00:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_manualjobapplication_interview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualjobapplication',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
