# Generated by Django 5.2.7 on 2026-01-19 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_add_phone_to_contact_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyCaseLoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.CharField(help_text='Case ID from the Court', max_length=100)),
                ('court_name', models.CharField(max_length=200)),
                ('court_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='on_track', help_text='Initial status assigned by Agency', max_length=50)),
                ('email', models.EmailField(help_text='Email of the offender/user', max_length=254)),
                ('is_registered', models.BooleanField(default=False, help_text='True if a matching User account has been found/linked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_loads', to='users.agency')),
                ('matched_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_case_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('agency', 'case_id')},
            },
        ),
    ]
