# Generated by Django 5.2.7 on 2026-02-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencycaseload',
            name='email',
            field=models.EmailField(db_index=True, help_text='Email of the offender/user', max_length=254),
        ),
    ]
